/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../../components/menu/aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./../../components/header/header.vue')['default']
    Header_help: typeof import('./../../components/header/cpn/header_help.vue')['default']
    Header_info: typeof import('./../../components/header/cpn/header_info.vue')['default']
    Header_nav: typeof import('./../../components/header/cpn/header_nav.vue')['default']
    IconCommunity: typeof import('./../../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../../components/icons/IconTooling.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCaretLeft: typeof import('~icons/ep/caret-left')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpRank: typeof import('~icons/ep/rank')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./../../components/menu/cpn/subMenu.vue')['default']
  }
}
